---
- name: "System | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: system_distribution_config

- name: "System | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: system_distribution_config.stat.exists

- name: "System | Set hosts"
  ansible.builtin.template:
    dest: "/etc/hosts"
    src: hosts.j2
    mode: "0644"
  become: true
  when: not ansible_host_environment_is_wsl

- name: System | Detecting win32yank
  ansible.builtin.stat:
    path: /usr/local/bin/win32yank.exe
  register: win32yank_installed
  when: ansible_host_environment_is_wsl

