#!/bin/bash

print_usage() {
  printf "Usage: ... \n"
}

pComplexity=""
pLength=""
charSet=""

while getopts "c:l:" arg; do
  case "$arg" in
  c) pComplexity="$OPTARG" ;;
  l) pLength="$OPTARG" ;;
  *)
    print_usage
    exit 1
    ;;
  esac
done

if [[ -z "$pLength" ]]; then
  pLength=16
fi

if [[ $pComplexity == 1 ]]; then
  charSet="A-Za-z"
elif [[ $pComplexity == 2 ]]; then
  charSet="A-Za-z0-9"
elif [[ $pComplexity == 3 ]]; then
  charSet='!-~'
else
  charSet='!-~'
fi

tr -dc $charSet </dev/urandom | head -c $pLength
echo ''
